# Generated by Django 4.1.5 on 2023-01-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('altura', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, max_length=100)),
                ('nascimento', models.DateField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=1)),
                ('file', models.FileField(upload_to='upload/media')),
            ],
        ),
    ]
